server:
  port: 8090
spring:
  application:
    name: "employees"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: qa

management:
  endpoints:
    web:
      exposure:
        include: "*"

build:
  version: 3.0.0
