services:
  employees:
    image: khandelwalsumit/employee-service:1.0.0
    container_name: employees
    ports:
      - 8090:8090
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ems

  configserver:
    image: khandelwalsumit/config-server:5.0.0
    container_name: configserver
    ports:
      - 8071:8071
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/readiness | grep UP || exit 0"
      timeout: 10s
      retries: 5
      interval: 10s
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ems

networks:
  ems:
    driver: "bridge"